[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' https://vakilsearch.com data:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
